// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl96SD2pbHfYOSNnBK7Ngh3JXXIuR5vps',
    appId: '1:25758808966:web:0a5b3bf52e08c839ee0a07',
    messagingSenderId: '25758808966',
    projectId: 'reddit-clone-app-8a0ee',
    authDomain: 'reddit-clone-app-8a0ee.firebaseapp.com',
    storageBucket: 'reddit-clone-app-8a0ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZSVLL5D9tPE2BxBilUUzq1SQgzNYIXmg',
    appId: '1:25758808966:android:80223b6966b33d89ee0a07',
    messagingSenderId: '25758808966',
    projectId: 'reddit-clone-app-8a0ee',
    storageBucket: 'reddit-clone-app-8a0ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcUNnZkaDP6bscrGpz3hCpSCemiFNmeFo',
    appId: '1:25758808966:ios:0b76b8bf1cfa1b43ee0a07',
    messagingSenderId: '25758808966',
    projectId: 'reddit-clone-app-8a0ee',
    storageBucket: 'reddit-clone-app-8a0ee.appspot.com',
    iosClientId: '25758808966-tbt3m9el3d92uv5pkolg9s6dr4gisprn.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl96SD2pbHfYOSNnBK7Ngh3JXXIuR5vps',
    appId: '1:25758808966:web:fac1d830ae00f7c2ee0a07',
    messagingSenderId: '25758808966',
    projectId: 'reddit-clone-app-8a0ee',
    authDomain: 'reddit-clone-app-8a0ee.firebaseapp.com',
    storageBucket: 'reddit-clone-app-8a0ee.appspot.com',
  );
}
